# Generated by Django 2.2.6 on 2019-11-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameShop', '0002_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
