# Generated by Django 2.2.6 on 2019-11-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameShop', '0005_auto_20191127_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
