# Generated by Django 2.2.6 on 2019-11-27 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameShop', '0006_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='game_rate',
        ),
        migrations.RemoveField(
            model_name='games',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
