# Generated by Django 2.2.6 on 2019-11-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameShop', '0007_auto_20191127_0742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='games',
            name='game_rate',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
