# Generated by Django 2.2.6 on 2019-11-29 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GameShop', '0011_auto_20191129_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_rate',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_number', models.FloatField()),
                ('rating_games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameShop.Games')),
                ('rating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
