# Generated by Django 2.2.6 on 2019-11-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameShop', '0012_auto_20191129_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
