# Generated by Django 2.2.6 on 2019-12-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameShop', '0013_rating_rated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='date_ordered',
        ),
        migrations.AlterField(
            model_name='games',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
