# Generated by Django 2.2.6 on 2019-12-02 15:17

import GameShop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameShop', '0014_auto_20191202_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=GameShop.models.upload_location),
        ),
    ]
