# Generated by Django 2.2.6 on 2019-12-02 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameShop', '0015_auto_20191202_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
    ]
