# Generated by Django 2.2.6 on 2019-12-03 04:27

import GameShop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameShop', '0017_profile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=GameShop.models.upload_location),
        ),
    ]
