# Generated by Django 2.2.6 on 2019-12-03 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameShop', '0018_auto_20191203_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='image',
        ),
    ]
