# Generated by Django 2.2.6 on 2019-12-03 18:08

import GameShop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameShop', '0019_remove_games_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=GameShop.models.upload_location),
        ),
    ]
