# Generated by Django 2.2.6 on 2019-12-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameShop', '0020_games_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='description',
            field=models.TextField(default=123, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='games',
            name='game_rate',
            field=models.FloatField(null=True),
        ),
    ]
