# Generated by Django 2.2.6 on 2019-12-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameShop', '0023_auto_20191204_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='news_image'),
        ),
    ]
