# Generated by Django 2.2.6 on 2019-12-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameShop', '0025_auto_20191204_0712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='games',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='game',
            field=models.ManyToManyField(blank=True, null=True, to='GameShop.Games'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
