# Generated by Django 2.2.6 on 2019-12-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameShop', '0026_auto_20191204_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_image'),
        ),
    ]
