# Generated by Django 2.2.6 on 2019-12-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameShop', '0028_auto_20191204_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='game',
        ),
    ]
