# Generated by Django 2.2.6 on 2019-12-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameShop', '0030_category_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='price',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
    ]
